import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true


option_as_alt = "Both"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono"

